### ISSUE TITLE
Reporte de diagrama de componentes 

### ISSUE THREAD

**Issue by SandyMarissaGs** [SistemasTecTlaxiaco/actividad-10-practica-de-arquitectura-equipo-s-b-j#1]
[REPORTE_DIAGRAMA DE COMPONENTES.pdf](https://github.com/user-attachments/files/18042046/REPORTE_DIAGRAMA.DE.COMPONENTES.pdf)

Diagrama de componentes en la wiki:
https://github.com/SistemasTecTlaxiaco/CryptoStream/wiki/9.-Arquitectura-de-Software-para-Web-3.0

**Comment by Anakimberly** [comment]
De acuerdo a la rubrica obtuvieron 29% de 30%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
